CREATE TABLESPACE TPCC DATAFILE '+DS0/tpcc.dtf' SIZE 30G REUSE
	AUTOEXTEND OFF EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M SEGMENT SPACE MANAGEMENT AUTO;
ALTER TABLESPACE TPCC ADD DATAFILE '+DS0/tpcc02.dtf' SIZE 30G  REUSE;
